label s1e1:
    "It was hard to say who was more surprised when I picked Neil."
    "Cliff made a sound like he\'d just been punched. Vince winced."
    "(Sorry to disappoint him. He\'s kinda cute.)"
    "Donovan tries to cover with a cough, but ended up hacking like he had TB..."
    "Uncle Charlie just chuckled, then groaned."
    ch "Thanks for the laugh, kiddo, but let\'s can it with the jokes for a while. Stitches, y\'know."
    me "Sorry, Uncle Charlie. But I\'m serious."
    "Neil hadn\'t moved a muscle since I spoke his name. Those icy blue eyes of his were riveted onto my face like he was seeing it for the first time."
    c "Honest? Neil?"
    me "No joke. Neil\'s my pick."
    n "You don\'t want me."
    me "Who says?"
    n "I say."
    me "Well, it isn\'t your choice, is it? It\'s mine. You were in the war, so you can handle yourself, and I think you\'ve got decent manners when you\'re not in a snit..."
    v "Besides, her momma always wanted her little girl to marry a doctor. Ow! Hey, Cliff, watch where you\'re stickin\' them elbows!"
    c "Watch how you\'re running your mouth."
    v "You were the one who asked if she was serious!"
    me "Keep it down to a dull roar over there, fellas. We\'re in a hospital."
    "(Did I just detect the slightest smile on Neil's face?)"
    n "Charlie, tell her it\'s a bad idea."
    Charlie "If I thought it was, I would...but thinkin\'' on it a bit, I think it\'s a pretty savvy move."
    Charlie "She\'s gonna need somebody with a good head on his shoulders watchin\' out for her. You\'re a little older...seen more of the world..."
    Vince "That\'s his way of sayin\' he figures you\'re the least likely to get up to no good with his niece."
    Charlie "Safer with him than with you, that\'s for damn sure."
    "Everyone except Neil and Vince laughed. Neil's eyes left mine for a second to flick over Vince."
    "Then, he turned to Charlie."
    Neil "Charlie, I must decline. [fName] will prove very...capable when it comes to running the Ice Box, I\'m sure..."
    "(He\'s selling soap...and he\'s not very good at it.)"
    Neil "...but I have neither the time or inclination to act as nursemaid..."
    me "Hey! Let\'s get one thing straight, DOCTOR...Charlie\'s the one who says I need a right hand guy here, not me."
    me "...an\' what I don\'t know about taking care of myself wouldn\'t fill up my cousin Gertrude\'s clutch..."
    Neil "Is that so? Ever run a business before?"
    me "No, but I have two years of business college..."
    Neil "Did you graduate?"
    me "No, but..."
    Neil "And then there are the special skills required of a speakeasy manager. Ever stop a fight?"
    me "Well, I talked Martin Phelps and Teddy Denby out of slugging it out once..."
    Neil "Stopping two high school boys from tussling over your favors isn\'t the same thing as breaking up two angry, drunken men."
    me "That\'s true, but..."
    Neil "Can you shoot a gun?"
    me "Well...no..."
    Neil "Can you drive a car?"
    me "I...ah..."
    Neil "So, I\'ll be expected to be your chauffeur, too. This just keeps getting better and better."
    "Just then Charlie started groaning again and everybody piped down."
    Neil "In deference to you, Charlie, I\'ll refrain from asking her about more intimate matters, but I think I\'ve made my point."
    "I must\'ve been beet red, even in the dim light in that sick room."
    Charlie "Seems like she gives about as good as she gets. There\'s no reason she shoulda learned to shoot the way she\'s been brought up..."
    ch "...and I don\'t think women have any place behind the wheel OR in the voting booth, but Congress says otherwise, so that case is closed."
    Neil "But Charlie, she\'s not ready for the responsibility! That means she\'s in no need of a protector."
    ch "She\'s gonna get her chance at runnin\' things, Neil."
    ch "An\' since you\'re the only one of these guys who\'s got a chance of keeping\' up with her in the brains department, you\'re elected to see she gets her shot."
    "None of the other fellas took offense, seeing as it was Charlie saying it."
    Charlie "Now, quit your belly-aching and take her back to my place."
    Charlie "You stay at the house, [fName]. Mrs. Fitzhugh\'ll take good care of you so you can concentrate on the Box."
    Neil "Moretti, you take her. I\'m going to stay here and keep an eye on Charlie for a while..."
    Charlie "No you aren\'t. I\'ve got a hospital full of docs on my case, so you can do as you\'re told."
    "Sighing deeply, Neil turned to leave."
    Neil "I\'ll check in on you tomorrow, Charlie. Let\'s go, [fName]."
    "I gave Uncle Charlie a hasty kiss on the cheek, waved a quick goodbye to the rest and still had to hurry to catch up to Neil."
    "(Those long legs of his cover some ground!)"
    # bg change
    "He didn\'t hold the door for me. He barely even waited for me to be in the car before zooming off."
    menu drive_choice:
        'A: "You could be nicer."': ###########HEART CHOICE
            me "You could be nicer."
            "Neil just grunted."
            me "Trying to prove me wrong about you having manners?"
            "Nothing"
            me "So, you\'re from Boston."
            "He shot me a look, but said nothing."
            me "The Boston Brahmin accent. It\'s a dead giveaway. I\'m guessing you come from money?"
            "The silence continued."
            "(It\'s like talking to the Sphinx! We\'re almost there. I\'ve got to get a rise out of him somehow.)"
            "I scooted across the seat until I was right next to him..."
            "(Tried this with Teddy Denby once and it got me invited to go petting.)"
            "..and stuck my hand in his jacket, running my fingers across the very fine fabric of his expensive shirt."
            me "Do you carry a gun?"
            "He slapped my hand away."
            Neil "Keep your hands to yourself! Get back on your side of the seat!"
            "(So...NOT like Teddy Denby...)"
        'B: "Is my uncle going to be all right?"':
            Neil "He's been shot, but he's not dead yet...and I\'m not his doctor. Now you know almost as much as I do."
            me "I\'m guessing you have some relevant experience you can apply in this situation."
            Neil "I may, but I have no compelling reason to share it with you."
            "I dredged up a sniffle and pulled a hanky from my bag."
            me "So...just \'cause you don\'t like me...you\'re not going to tell me what you think about my...my Uncle\'s condition..."
            Neil "Don\'t pull the sob sister act with me! You hardly knew the man before being tossed on his doorstep this morning."
            "(Wow. Tough nut. Or maybe I\'M the tough nut for trying that act.)"
            "I packed my handkerchief away and glared at his profile as we zipped down the quiet streets."
            "(Getting close to Charlie\'s now.)"
            me "All right, fine. You don\'t like me much, but Charlie pays you for...something..."
            me "...and right now that something is keeping me from getting cracked and scrambled..."
            me "So, give me the silent treatment or speechify like William Jennings Bran, I don\'t care...just don\'t be a sourpuss while you\'re going about it!"
    "We pulled up to the curb in front of Charlie\'s house."
    me "What happened to all those nice manners?"
    Neil "Did I demonstrate any of them to you earlier this evening?"
    me "No...You were kind of a louse, if you want the truth, but I figured a fella from Boston money must\'ve been raised right."
    Neil "I was. And I learned something in the rarefied air of high society..."
    me "Yeah? Clue me in, Sherlock."
    Neil "Manners are deployed for the purpose of getting something one wants..."
    Neil "and I don\'t want anything from you."
    "(We\'ll see about that, doctor!)"
    "I climbed out of the car and was standing there, the door still open."
    me "I\'ll see you tomorrow, around lunchtime. You can take me to the Ice Box..."
    Neil "I\'m not your chauffeur. Call a cab."
    "He gassed it and took off. The passenger door slipped out of my hand and didn\'t slam shut until he took the curve."
    # BG change
    "I wanted to get a leg up on my first day, so I got to the Ice Box just after noon...HOURS before opening."
    "Cliff was stocking behind the bar. No shock there. But I was a little surprised to see Neil in the same perch he\'d occupied last night..."
    "...with a glass of bourbon in front of him."
    me "You get special drinking privileges? Are you on the clock?"
    Neil "Yes to your first question. And it\'s not your clock, so it\'s not your business."
    me "Give me the run-down on how things work around here."
    Neil "Customers pay for the privilege of coming in sober and leaving drunk."
    me "Thanks. Very helpful."
    Cliff "Come over to this side of the bar, [fName]. I\'ll give you the nickel tour."
    "Glaring at Neil, I did as Cliff suggested. He showed me the backroom first."
    Cliff "Little desk over there where Charlie does the book-keeping...Vince keeps us pretty well stocked with the good stuff...imported from Canada..."
    c "Charlie always tells the customers we don\'t drain the bathtub for our booze."
    me "What\'s the cot for? Do you sleep over?"
    c "Sometimes, when the weather\'s bad. But we got it one time for Vince. He needed a place to heal up an\' Neil said we shouldn\'t move him."
    me "Heal up?"
    Cliff "Vince...knows some dangerous people. Sometimes they don\'t play so nice."
    "He pointed out where the different types of booze were stored, front to back and top to bottom..."
    "..but I noticed a little cluster of bourbon bottles off by themselves with a big, hand-lettered sign hanging from the shelf below them: \"Private Stock. Do Not Touch\""
    me "What\'s that?"
    c "Neil\'s special reserve of bourbon. Vince brings it in from somewhere. He\'s been drinkin\' it since he got back from the war."
    "I saw a chance to satisfy my curiosity, so I took it."
    me "So...what\'s Neil\'s story? What does he DO around here?"
    "Cliff hesitated."
    c "That\'s between you \'n him. Let\'s just say...somebody\'s gotta patch Vince up when he has a run-in with those friends of his."
    "I grabbed the ledger from Charlie\'s desk. We moved back out to the bar. Vince was there."
    Vince "Cliff showing you the ropes?"
    Neil "Trying to avert her hanging herself, and us with her."
    me "Thanks for the vote of confidence."
    Neil "You thought I was being supportive?"
    me "What, you can\'t hear sarcasm when you\'re spifflicated?"
    Neil "I heard it, but with your corn-fed, homespun manners, I didn\'t think you\'d use it. I stand corrected."
    me "I\'d be surprised if you could stand at all."
    "Turning away from Neil, I buttonholed Vince and Cliff and asked them to give me a rundown on how the booze came in and went out."
    "(I really do need to understand this operation if I\'m going to do a good job.)"
    "After about thirty minutes of question-and-answer, referring to the ledger for specific numbers, I had a decent grasp of the business..."
    "...and it was very profitable. You make something illegal and the price goes up along with the risk, but once you\'ve figured out a way to manage the risk..."
    "...the sky\'s the limit. Charlie, Cliff, and Vince had a system in place keep the risk manageable."
    me "...50 I gather you ship most of the hard stuff in from Canada down the lake...but how about beer?"
    me "Doesn\'t seem like it\'d be profitable to ship that in, since it\'s so bulky in those kegs...an\' you don\'t buy from the big outfit here in town..."
    c "No. Don\'t like doing business with those guys an\' they\'ve left us alone so far."
    Cliff "We bring a lot of our beer in from small, home brewers in southern Illinois, but the quality...well, let\'s be nice and say it goes up and down..."
    Vince "Yeah. Up and down on a scale from horse piss to liquid sourdough. Can\'t see why anyone\'d drink it, but some do."
    me "Would it make sense to try and set up some locals to do the brewing...keep it close at hand so we could control quality?"
    "Vince looked at me with an appraising eye. He saw me looking at him and winked."
    Vince "Pretty savvy. The supplies are easy enough to get..."
    Vince "...an\' I could pull together enough people to do small batches in basements and such."
    "I did some quick calculations in my head and scribbled a number down."
    me "What do you think, Cliff? If this number is our monthly cost, can we make enough money selling beer to clear a profit?"
    c "If we can have a consistent brew, then we can for sure make a profit! People really miss good beer."
    "From his end of the bar, Neil suddenly piped up."
    Neil "Not even one day on the job and already making changes. We are truly and royally screwed."
    Vince "Why don\'t you lay off her, Dresner? She\'s got a good head on her shoulders."
    Neil "You know Vince is just sticking up for you because he\'s hoping to take you for a spin later. More flies with honey, if you know what I mean."
    "I ignored him, but to Vince, I whispered..."
    me "Why does he have to be such a high hat all the time?"
    Vince "You want something besides the cold shoulder from Neil, you\'re askin\' the wrong guy. I never cared enough to try an\' figure what makes him tick."
    # BG change
    "I worked with Cliff getting the club ready for opening."
    "The only time Neil moved was to go to the john, but every time I glanced over at him, he was looking at me."
    # BG change
    "At around eight, Andrew, our doorman, took his post and the clientele began to wander in. By ten, the place was jumping."
    Vince "Good crowd tonight. Guess they\'re here to see the new talent."
    me "Better give\'em a good show then. Want to dance?"
    Vince "Thought you\'d never ask."
    "We hit the dance floor and danced to {i}Black Bottom{/i} and then did the Charleston before Julius slowed things down."
    "Vince was eager to pull me in."
    menu dance_choice:
        'A: Beg off and get back to work.':
            "Instead of letting him, I pulled away."
            me "Been fun, but I\'ve got to circulate."
            c "C\'mon, doll! We\'re just getting started!"
            me "Put it in neutral, cowboy...I\'ve got work to do."
            Vince "You\'re goin\' to turn down some fun?"
            me "What did you think? My uncle\'s giving me a chance...I\'m going to take it! Now, shoo. Customers need my attention!"
        'B: Dance one more with him.':
            "(Aw, what the heck!)"
            "(Julius and the band started to play a tango. I was about to beg off, but Vince was too fast for me.)"
            "Next thing I knew, I was in his arms, our bodies pressed together."
            "(He really is good.)"
            me "Where\'d you lern the tango?"
            v "Watching Valentino in the movies."
            me "Seriously?"
            v "Saw Fource Horsemen of the Apocalypse fifteen times just for that scene. Tracked down the man himself when he was in town..."
            v "...bought him a drink, and he gave me a few pointers."
            "I missed a step."
            me "You met VALENTINO?"
            v "Bribed my way onto his floor in the Palmer House, then just knocked on his door."
            "(Gotta admire his brass.)"
            me "You coulda just taken dance lessons."
            v "Maybe...but it wouldna been as good a story."
        'C: Ask him to fetch you a drink.':
            me "Y\'know, I could use a drink. Would you get me a whiskey?"
            v "Up or on the rocks?"
            me "Straight up."
            v "That ain\'t no ladies drink."
            "I pinched his cheek."
            me "Maybe that\'s \'cause I ain\'t no lady."
    # BG change
    "Just then a beefy guy with a red face and a wrinkled jacket waved me over."
    Customer "Hey, sweetheart, you the boss of this joint? The one they\'re callin\' the Ice Box Flapper?"
    "(I\'ve already got a nickname?!)"
    me "The handle\'s news to me, but yeah, I\'m the manager."
    Customer "I\'m in from Cleveland. Big Jim Blaylock\'s the name. Men\'s haberdashery\'s my game..."
    "(Bad advertisement for his own product if you ask me. I\'ve seen better suits on carnival barkers.)"
    Customer "These drinks of yours are more water than booze."
    me "I\'m sorry you\'re not satisfied, sir. What are you drinking?"
    Customer "Gin Rickey."
    "I headed over to the bar to have a word with Cliff, then headed back to the table."
    me "Do you make a habit of trying to take advantage of young women, Big Jim?"
    Customer "What?"
    me "Well, my bartender tells me you\'ve been drinking these for the last two hours, no complaints...until you got into a conversation with some of our regulars..."
    me "...and they told you today was my first day running the place."
    me "Now, my bartender, who I have every reason to trust, showed me how he makes a Gin Rickey. He measures. No short pours at the Ice Box..."
    me "So either my guys are putting their jobs at risk by lying to me or some sad sack salesman from Cleveland is trying to pull a fast one on the new kid."
    me"Want to guess where I\'m putting MY money?"
    Customer "If THIS is the way you treat your customers, you\'ll be out of business in a week! I\'ll be going!"
    "He tried to bluster his way out the door, but Andrew, smiling but very large, blocked him."
    me "You can go soon as you pay your bill...plus a hefty tip for the waiter and the bartender while you\'re at it."
    "He huffed and puffed some more, but he was standing in a straw house and he knew it."
    "Big Jim hit the pavement a minute later, red-faced and lighter by twenty bucks."
    "I caught a glimpse of Neil out of the corner of my eye."
    "(I\'ll be damned if he isn\'t smiling!)"
    "I marched over to him."
    me "You going to admit I can handle myself after all?"
    "Neil raised his glass to me. He looked remarkably steady for a guy\' who\'d been drinking all day."
    Neil "All I\'ll admit is, the particular train to hell we\'re on may not be an express."
    "And THAT was all I got out of him. He was still sitting there, staring into his bourbon, when we closed up in the wee hours."
    "Vince sidled up to me and slipped a hand around my waist."
    "(Well, that\'s pretty familiar! Not unwelcome...but still...)"
    Vince "Should I take you home, doll?"
    "(Hmmm.)"
    Neil "That isn\'t going to fly, Moretti. If Charlie wouldn\'t approve, I don\'t approve. She\'ll go with me."
    "(Really? NOW he decides to act like my guardian angel?!)"
    me "You couldn\'t palm me off fast enough last night!"
    Neil "A foolish consistency is the hobgoblin of small minds. Oscar Wilde."
    Vince "You sober enough to walk, Oscar?"
    c "He hasn\'t had a freshener since before midnight. Sober as a judge, from what I can see."
    Neil "It\'s settled, then. Cliff\'ll finish up. Grab your bag and let\'s go."
    "Sighing to myself, I shrugged in Vince\'s direction and followed Neil out the door."
    "(It\'s sweet that Vince looks so disappointed, but I\'m not ready to climb on that train, so this is probably for the best. Darn it.)"
    $ next_chapter = next_chapter + 1
    jump next_chapter_menu